name: Integration Tests

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build and run integration tests
        run: |
          docker compose -f infra/test/docker-compose.yaml up --build --abort-on-container-exit --remove-orphans integration-runner
          docker compose -f infra/test/docker-compose.yaml down
