name: E2E Tests
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  unit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set WEATHER_API_KEY in .env
        run: |
          mkdir -p infra/test/php
          touch infra/test/php/.env
          grep -q '^WEATHER_API_KEY=' infra/test/php/.env && \
            sed -i "s/^WEATHER_API_KEY=.*/WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }}/" infra/test/php/.env || \
            echo "WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }}" >> infra/test/php/.env

      - name: Build and run e2e tests
        run: |
          docker compose -f infra/test/docker-compose.yaml up --build --abort-on-container-exit --remove-orphans e2e-runner
          docker compose -f infra/test/docker-compose.yaml down
