name: Code Quality

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build composer container
        run: docker compose build composer

      - name: Install dependencies
        run: docker compose run --rm composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Run code style check and fix (PHPCS)
        run: docker compose run --rm composer lint

      - name: Run static analysis (PHPStan)
        run: docker compose run --rm composer analyse